<?php namespace Zingabory\Extendblog\Components;

use Cms\Classes\ComponentBase;
use Cms\Classes\Page;

class BlogTagSearch extends \Bedard\BlogTags\Components\BlogTagSearch
{
    public function onLoadPage($page = false)
    {
        parent::onLoadPage($page); // TODO: Change the autogenerated stub

        $posts = $this->tag->posts()->with('categories')->get();

        /*
        * Add a "url" helper attribute for linking to each post and category
        */

        $posts->each(function ($post) {
            $post->setUrl($this->property('postPage'), $this->controller);

            $post->categories->each(function ($category) {
                $category->setUrl($this->property('categoryPage'), $this->controller);
            });
        });

        $this->posts = $posts;
    }

    public function defineProperties()
    {
        $prop = parent::defineProperties();

        $add = [
            'categoryPage' => [
                'title' => 'rainlab.blog::lang.settings.posts_category',
                'description' => 'rainlab.blog::lang.settings.posts_category_description',
                'type' => 'dropdown',
                'default' => 'blog/blog-category',
                'group' => 'Links'
            ],
            'postPage' => [
                'title' => 'rainlab.blog::lang.settings.posts_post',
                'description' => 'rainlab.blog::lang.settings.posts_post_description',
                'type' => 'dropdown',
                'default' => 'blog/post',
                'group' => 'Links'
            ]
        ];
        return  $prop + $add;
    }


    public function getCategoryPageOptions()
    {
        return Page::sortBy('baseFileName')->lists('baseFileName', 'baseFileName');
    }

    public function getPostPageOptions()
    {
        return Page::sortBy('baseFileName')->lists('baseFileName', 'baseFileName');
    }
}